---
- hosts: all
  become: true
  tasks:
    - name: make sure the packages openssh and openssl are uptodate
      ansible.builtin.apt:
        name: "{{ item }}"
        state: latest
      loop:
        - openssh
        - openssl
        # error handling 
      ignore_errors: yes
    - name: update machine
      ansible.builtin.command: apt-get update
    - name: verfiy docker installed
      ansible.builtin.command: docker --version
      # here register is routing all the output from the above command to the variable output
      # and we are using when to check if docker is not installed be have to install the docker 
      register: output
      ignore_errors: yes
    - name: install docker
      ansible.builtin.apt:
       name: docker.io
       state: present
      when:
        output.failed
